/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/book/$id': typeof BookIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/book/$id': typeof BookIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/book/$id': typeof BookIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/catalog'
    | '/login'
    | '/profile'
    | '/publish'
    | '/signup'
    | '/book/$id'
    | '/messages/$id'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catalog'
    | '/login'
    | '/profile'
    | '/publish'
    | '/signup'
    | '/book/$id'
    | '/messages/$id'
    | '/messages'
  id:
    | '__root__'
    | '/catalog'
    | '/login'
    | '/profile'
    | '/publish'
    | '/signup'
    | '/book/$id'
    | '/messages/$id'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CatalogRoute: typeof CatalogRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PublishRoute: typeof PublishRoute
  SignupRoute: typeof SignupRoute
  BookIdRoute: typeof BookIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CatalogRoute: CatalogRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PublishRoute: PublishRoute,
  SignupRoute: SignupRoute,
  BookIdRoute: BookIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
